// Shared nationality options used by every nationality picker (member create/edit,
// public registration, invoice add-member). The stored value is the Arabic word
// so existing data and the reports grouping stay consistent; the English label is
// only for display when the UI is in English.
export const NATIONALITY_OPTIONS = [
  // Gulf & Arab world (most common first)
  { value: 'سعودي', en: 'Saudi' },
  { value: 'مصري', en: 'Egyptian' },
  { value: 'إماراتي', en: 'Emirati' },
  { value: 'كويتي', en: 'Kuwaiti' },
  { value: 'قطري', en: 'Qatari' },
  { value: 'بحريني', en: 'Bahraini' },
  { value: 'عُماني', en: 'Omani' },
  { value: 'يمني', en: 'Yemeni' },
  { value: 'أردني', en: 'Jordanian' },
  { value: 'فلسطيني', en: 'Palestinian' },
  { value: 'لبناني', en: 'Lebanese' },
  { value: 'سوري', en: 'Syrian' },
  { value: 'عراقي', en: 'Iraqi' },
  { value: 'سوداني', en: 'Sudanese' },
  { value: 'ليبي', en: 'Libyan' },
  { value: 'تونسي', en: 'Tunisian' },
  { value: 'جزائري', en: 'Algerian' },
  { value: 'مغربي', en: 'Moroccan' },
  { value: 'موريتاني', en: 'Mauritanian' },
  { value: 'صومالي', en: 'Somali' },
  { value: 'جيبوتي', en: 'Djiboutian' },
  { value: 'قمري', en: 'Comoran' },
  { value: 'عربي', en: 'Arab' },

  // Asia
  { value: 'هندي', en: 'Indian' },
  { value: 'باكستاني', en: 'Pakistani' },
  { value: 'بنغلاديشي', en: 'Bangladeshi' },
  { value: 'سريلانكي', en: 'Sri Lankan' },
  { value: 'نيبالي', en: 'Nepali' },
  { value: 'أفغاني', en: 'Afghan' },
  { value: 'إيراني', en: 'Iranian' },
  { value: 'تركي', en: 'Turkish' },
  { value: 'إندونيسي', en: 'Indonesian' },
  { value: 'ماليزي', en: 'Malaysian' },
  { value: 'فلبيني', en: 'Filipino' },
  { value: 'صيني', en: 'Chinese' },
  { value: 'ياباني', en: 'Japanese' },
  { value: 'كوري جنوبي', en: 'South Korean' },
  { value: 'كوري شمالي', en: 'North Korean' },
  { value: 'تايلندي', en: 'Thai' },
  { value: 'فيتنامي', en: 'Vietnamese' },
  { value: 'بورمي', en: 'Burmese' },
  { value: 'كمبودي', en: 'Cambodian' },
  { value: 'لاوسي', en: 'Lao' },
  { value: 'سنغافوري', en: 'Singaporean' },
  { value: 'منغولي', en: 'Mongolian' },
  { value: 'كازاخستاني', en: 'Kazakh' },
  { value: 'أوزبكي', en: 'Uzbek' },
  { value: 'طاجيكي', en: 'Tajik' },
  { value: 'تركماني', en: 'Turkmen' },
  { value: 'قيرغيزي', en: 'Kyrgyz' },
  { value: 'أذربيجاني', en: 'Azerbaijani' },
  { value: 'أرميني', en: 'Armenian' },
  { value: 'جورجي', en: 'Georgian' },

  // Europe
  { value: 'بريطاني', en: 'British' },
  { value: 'إيرلندي', en: 'Irish' },
  { value: 'فرنسي', en: 'French' },
  { value: 'ألماني', en: 'German' },
  { value: 'إيطالي', en: 'Italian' },
  { value: 'إسباني', en: 'Spanish' },
  { value: 'برتغالي', en: 'Portuguese' },
  { value: 'هولندي', en: 'Dutch' },
  { value: 'بلجيكي', en: 'Belgian' },
  { value: 'سويسري', en: 'Swiss' },
  { value: 'نمساوي', en: 'Austrian' },
  { value: 'سويدي', en: 'Swedish' },
  { value: 'نرويجي', en: 'Norwegian' },
  { value: 'دنماركي', en: 'Danish' },
  { value: 'فنلندي', en: 'Finnish' },
  { value: 'آيسلندي', en: 'Icelandic' },
  { value: 'بولندي', en: 'Polish' },
  { value: 'تشيكي', en: 'Czech' },
  { value: 'سلوفاكي', en: 'Slovak' },
  { value: 'مجري', en: 'Hungarian' },
  { value: 'روماني', en: 'Romanian' },
  { value: 'بلغاري', en: 'Bulgarian' },
  { value: 'يوناني', en: 'Greek' },
  { value: 'أوكراني', en: 'Ukrainian' },
  { value: 'روسي', en: 'Russian' },
  { value: 'بيلاروسي', en: 'Belarusian' },
  { value: 'صربي', en: 'Serbian' },
  { value: 'كرواتي', en: 'Croatian' },
  { value: 'سلوفيني', en: 'Slovenian' },
  { value: 'بوسني', en: 'Bosnian' },
  { value: 'ألباني', en: 'Albanian' },
  { value: 'مقدوني', en: 'Macedonian' },
  { value: 'ليتواني', en: 'Lithuanian' },
  { value: 'لاتفي', en: 'Latvian' },
  { value: 'إستوني', en: 'Estonian' },
  { value: 'مالطي', en: 'Maltese' },
  { value: 'قبرصي', en: 'Cypriot' },

  // Americas
  { value: 'أمريكي', en: 'American' },
  { value: 'كندي', en: 'Canadian' },
  { value: 'مكسيكي', en: 'Mexican' },
  { value: 'برازيلي', en: 'Brazilian' },
  { value: 'أرجنتيني', en: 'Argentine' },
  { value: 'تشيلي', en: 'Chilean' },
  { value: 'كولومبي', en: 'Colombian' },
  { value: 'بيروفي', en: 'Peruvian' },
  { value: 'فنزويلي', en: 'Venezuelan' },
  { value: 'إكوادوري', en: 'Ecuadorian' },
  { value: 'بوليفي', en: 'Bolivian' },
  { value: 'باراغواياني', en: 'Paraguayan' },
  { value: 'أوروغواياني', en: 'Uruguayan' },
  { value: 'كوبي', en: 'Cuban' },
  { value: 'دومينيكاني', en: 'Dominican' },
  { value: 'غواتيمالي', en: 'Guatemalan' },
  { value: 'هندوراسي', en: 'Honduran' },
  { value: 'بنمي', en: 'Panamanian' },
  { value: 'كوستاريكي', en: 'Costa Rican' },
  { value: 'جامايكي', en: 'Jamaican' },
  { value: 'هايتي', en: 'Haitian' },

  // Africa
  { value: 'نيجيري', en: 'Nigerian' },
  { value: 'غاني', en: 'Ghanaian' },
  { value: 'كيني', en: 'Kenyan' },
  { value: 'إثيوبي', en: 'Ethiopian' },
  { value: 'إريتري', en: 'Eritrean' },
  { value: 'تنزاني', en: 'Tanzanian' },
  { value: 'أوغندي', en: 'Ugandan' },
  { value: 'جنوب أفريقي', en: 'South African' },
  { value: 'زيمبابوي', en: 'Zimbabwean' },
  { value: 'زامبي', en: 'Zambian' },
  { value: 'أنغولي', en: 'Angolan' },
  { value: 'موزمبيقي', en: 'Mozambican' },
  { value: 'كاميروني', en: 'Cameroonian' },
  { value: 'سنغالي', en: 'Senegalese' },
  { value: 'مالي', en: 'Malian' },
  { value: 'نيجري', en: 'Nigerien' },
  { value: 'تشادي', en: 'Chadian' },
  { value: 'بوركينابي', en: 'Burkinabè' },
  { value: 'غيني', en: 'Guinean' },
  { value: 'إيفواري', en: 'Ivorian' },
  { value: 'توغولي', en: 'Togolese' },
  { value: 'بنيني', en: 'Beninese' },
  { value: 'رواندي', en: 'Rwandan' },
  { value: 'بوروندي', en: 'Burundian' },
  { value: 'كونغولي', en: 'Congolese' },
  { value: 'غابوني', en: 'Gabonese' },
  { value: 'مدغشقري', en: 'Malagasy' },
  { value: 'موريشيوسي', en: 'Mauritian' },
  { value: 'سيشيلي', en: 'Seychellois' },
  { value: 'بوتسواني', en: 'Botswanan' },
  { value: 'ناميبي', en: 'Namibian' },
  { value: 'مالاوي', en: 'Malawian' },
  { value: 'ليبيري', en: 'Liberian' },
  { value: 'سيراليوني', en: 'Sierra Leonean' },
  { value: 'غامبي', en: 'Gambian' },

  // Oceania
  { value: 'أسترالي', en: 'Australian' },
  { value: 'نيوزيلندي', en: 'New Zealander' },
  { value: 'فيجي', en: 'Fijian' },
];

export const nationalityLabel = (value, language) => {
  const opt = NATIONALITY_OPTIONS.find((o) => o.value === value);
  if (!opt) return value || '';
  return language === 'en' ? opt.en : opt.value;
};
